server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mysecurity?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis:
  type-aliases-package: com.jie.pojo,com.jie.vo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*Mapper.xml



# log4j
logging:
  level:
    com.jie.dao: debug
